### ISSUE TITLE
[Bug]: Shopify config and product store not displayed in menu footer and on settings page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/job-manager#233]
## Current behavior

After multiple login, the shopify product store and config information is not displayed on the menu footer

## Expected behavior

In every case, the information should be properly rendered.

## Steps to reproduce the issue

- Login into job-manager
- See that shopify information is correctly loaded
- Logout and login again
- Observe that the shopify information is not loaded correctly

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Screenshot:

![image](https://user-images.githubusercontent.com/41404838/188121957-5af5844e-21d4-49b2-8012-8ea2200f5534.png)

![image](https://user-images.githubusercontent.com/41404838/188121989-0023f8c0-4bf9-46dc-ab98-647307df89b8.png)

**Comment by k2maan** [comment]
Fixed by #310
