### ISSUE TITLE
Job not search by full job name

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/job-manager#253]
## Current behavior

In pipeline tab when we search job with a full job name in 'search job'.
It doesn't find a job and shows 'There is no job pending right now' .

## Steps to reproduce the issue

E.g   Search  'Add pre-order tags' in the 'search job' space  of pipeline tab
    Job is not found 

There are only specific keywords from which we can search job.

**Comment by adityasharma7** [comment]
@shashwatbangar

**Comment by Pragyad07** [comment]
On exploring more,identified that job can be searched in pipeline tab with description of job instead of job name.
