### ISSUE TITLE
Multiple date time instances on mobile when using trigger for modal

### ISSUE THREAD

**Issue by shashwatbangar** [hotwax/job-manager#261]
## Current behavior

When we use trigger for modal on Job Details page, closing date time modal shows empty modal

## Expected behavior

When using trigger, only one modal should get opened

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
not able to reproduce
