### ISSUE TITLE
Selecting Current date while scheduling a job 

### ISSUE THREAD

**Issue by Pragyad07** [hotwax/job-manager#270]
## Current behavior

While scheduling the job, the current date is highlighted but not selected. So, when the time is selected and set to scheduled it doesn't get scheduled.  
Each time, the date needs to select whether it is by default the current date.
## Expected behavior

While Scheduling a job, by default current date should be selected and only time needs to be set.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment]
I unassigned myself as I cannot replicate the error in my system locally.
