### ISSUE TITLE
Last run doesn't shows previous occurrences for jobs of Initial load page

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/job-manager#303]
## Current behavior

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/15027245/204760614-b56c3814-1baa-439b-98c4-edab23fc0af3.png">

## Steps to reproduce the issue

1. Navigate to the Initial Load page.
2. Click Import products in Bulk, job configuration chip will appear
Last run shows no occurrence even if there were jobs scheduled earlier 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by shashwatbangar** [comment]
Putting this issue on hold as currently we do not have any field which shows last run time of a job for IntialLoad jobs
