### ISSUE TITLE
Upgrade axios to v1.2.0 (latest )

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/job-manager#306]
## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by shashwatbangar** [comment]
Reference - https://www.npmjs.com/package/axios/v/1.2.1

**Comment by shashwatbangar** [comment]
Currently, axios-cache-adapter internally uses axios v0.21.1 & we want to upgrade axios to 1.2.1 which creates conflit in axios-cache-adapter plugin. Thus currently we cannot upgrade axios while using this plugin.

**Comment by adityasharma7** [comment]
It seems the Axios cache adapter is no longer maintained
https://www.npmjs.com/package/axios-cache-adapter
https://github.com/RasCarlito/axios-cache-adapter/pull/261

We could check for some other plugins, and possible candidates could be:

https://axios-cache-interceptor.js.org/config
https://github.com/arthurfiorette/axios-cache-interceptor
https://www.npmjs.com/package/axios-cache-interceptor

https://github.com/AlbinoDrought/cachios
https://www.npmjs.com/package/cachios
https://github.com/kuitos/axios-extensions#cacheadapterenhancer

**Comment by k2maan** [comment]
Inspected `axios-cache-interceptor`, `cachios` and `axios-extensions` and so, checked possible candidacy with `axios-cache-interceptor` as it supports the latest axios version. 

Yet, could not find proper detailed documentation on it and hence, could not implement it.
