### ISSUE TITLE
Menu footer improvement

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/job-manager#316]
## What is the motivation for adding/enhancing this feature?

The menu footer should have the option to change product store and Shopify config when there are multiple options. By default product options should be there and if there are multiple product stores & Shopify config then only product store options should exist

For most of the cases either there will be multiple stores or the shopify configs. In any of the scenario right configuration should be there in menu footer

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by k2maan** [comment]
@adityasharma7 sir, currently we also have the "None" option for store selection, which means there will always be two options available to select. So, do we have to honour the "None" option as well and give the functionality to choose "None" or the other option in the footer or shall we ignore the "None" option and show only the other store only?
