### ISSUE TITLE
Use HTTP GET method for all the API calls for getting data

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/job-manager#325]
## Current behavior

We initially faced issue passing complex data like object, array etc in GET method, and used POST method. With https://github.com/hotwax/job-manager/pull/185, this has been fixed, use GET method to all the API calls that requires data fetching.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by shashwatbangar** [comment]
Reference:
https://www.npmjs.com/package/qs
