### ISSUE TITLE
Create static UI of ERP, POS and WMS page

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/job-manager#365]
## What is the motivation for adding/enhancing this feature?

https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=22608%3A75836&t=w8zVQ3iY2W65ky59-0

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
closing issue, not needed anymore
