### ISSUE TITLE
While saving a batch for brokering service, save button does not work

### ISSUE THREAD

**Issue by appurvajain** [hotwax/job-manager#387]
## Current behavior
 When we create a batch for the broker order service in the Job Manager, the save button does not work.

## Expected behavior
Tested this on demo-oms instance, and while saving a batch it should get saved and the jobs should be scheduled.

## Steps to reproduce the issue
1. Login to the Job Manager application.
2. Go to the orders page and click on add + button under routing to add a brokering batch.
3. When you put in all the details, click on the save button.
4. The save button does not work as the dialog box remains open and no message appears.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
@appurvajain Can you add steps to reproduce the issue?

**Comment by appurvajain** [comment]
This is fixed on dev instance, therefore closing this issue after discussion.

**Comment by ymaheshwari1** [comment]
Fixed in this PR: https://github.com/hotwax/job-manager/pull/375
