### ISSUE TITLE
Card actions on the running page displaying incorrectly

### ISSUE THREAD

**Issue by appurvajain** [hotwax/job-manager#428]
## Current behavior
The footer actions on the running page are rendered incorrectly.

We will solve the issue of badge showing compressed separately
<img width="1440" alt="Screenshot 2023-04-07 at 5 50 52 PM" src="https://user-images.githubusercontent.com/113335194/230608074-d2b507ef-a11e-49ea-8dd6-aabe067b8d5f.png">

**Comment by adityasharma7** [comment]
UI issue. Happens on pending jobs as well
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/15027245/230609116-bc7a8f0a-47c9-4bbb-ab74-e3772f2c32ee.png">

**Comment by dt2patel** [comment]
updated the original issue. lets focus on the extra buttons

**Comment by dt2patel** [comment]
Assigned to @k2maan instead of @adityasharma7

**Comment by dt2patel** [comment]
I think this has been fixed, I saw the running tab earlier and this UI issue was fixed. closing issue.
