### ISSUE TITLE
Delete getPaidTransactionsAndCreateOrderPayment service from the Job Manager

### ISSUE THREAD

**Issue by appurvajain** [hotwax/job-manager#448]
## What is the motivation for adding/enhancing this feature?
Delete getPaidTransactionsAndCreateOrderPayment service which is visible as payment status on the orders page from the Job Manager

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
Does this service not work? What’s wrong with it? Or do we get this through order updates now?

**Comment by appurvajain** [comment]
This service cannot be run from the Job Manager as it is a async service and requires parametre whenever run. We need to give order ID which we cannot do from the Job Manager.

Discussed this with Deepak sir as well.

**Comment by SandeepRajput20** [comment]
I would like to work on this issue.

**Comment by ymaheshwari1** [comment]
> I would like to work on this issue.

Sure, go ahead.

**Comment by adityasharma7** [comment]
> Does this service not work? What’s wrong with it? Or do we get this through order updates now?

@dt2patel 
As mentioned by @appurvajain, the service works for a single order and is used internally. We have a webhook that takes care of it.  Should I move ahead with merging the PR?

**Comment by dt2patel** [comment]
Sure @adityasharma7 thanks for the clarification
