### ISSUE TITLE
Job scheduled on the misc job page does not show frequency on the job cart

### ISSUE THREAD

**Issue by appurvajain** [hotwax/job-manager#458]
## Current behavior
When we schedule a job from the misc job page and we open the job cart to see the frequency it is scheduled at, the frequency remains blank. Please find the screenshot below.
![Screenshot 2023-04-26 at 7 06 07 PM](https://user-images.githubusercontent.com/113335194/234593139-7f9435ec-f6f1-4814-beaf-7c4c4fd416ed.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by adityasharma7** [comment]
This is fixed with https://github.com/hotwax/job-manager/pull/480/files
