### ISSUE TITLE
On the misc jobs page, scrolling the page is giving back error

### ISSUE THREAD

**Issue by appurvajain** [hotwax/job-manager#459]
## Current behavior
When we scroll the jobs in the misc jobs page, it is giving back error of there are no miscellaneous jobs right now

**Comment by dt2patel** [comment]
@appurvajain can you attach a video of how to reproduce this issue?

**Comment by appurvajain** [comment]
This issue has been fixed. Closing this issue after verification.

**Comment by appurvajain** [comment]
Uploading Screen Recording 2023-06-12 at 11.50.24 AM.mov…
