### ISSUE TITLE
Job disappears after canceling on mobile view

### ISSUE THREAD

**Issue by dt2patel** [hotwax/job-manager#462]
## Current behavior

On mobile devices, after canceling a job, the job details disappear from the page

![image](https://user-images.githubusercontent.com/60128132/235453460-76db210a-9980-4d61-945b-45e7579ec1fd.png)

**Comment by dt2patel** [comment]
Attaching video for reference as well
https://user-images.githubusercontent.com/60128132/235671820-be9a1ee0-4770-4daf-b1a1-43012c8c32ad.MOV

**Comment by appurvajain** [comment]
This is happening on desktop as well. Just noticed yesterday.
