### ISSUE TITLE
Run Now not working for already scheduled job

### ISSUE THREAD

**Issue by appurvajain** [hotwax/job-manager#525]
## Current behavior
When we click on 'Run Now' for the jobs that are already scheduled and are visible on the pipeline page, the job fails.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by palash018** [comment]
is this issue fixed? i can't reproduce this Jobs are running fine after run now in my case

**Comment by Dhiraj1405** [comment]
@appurvajain It is fixed now. Try reproducing it and let us know if we can close this issue
