### ISSUE TITLE
Rejected order brokering not opening

### ISSUE THREAD

**Issue by dt2patel** [hotwax/job-manager#549]
## Current behavior

Rejected order brokering job is not showing up even though there is job data for it. upon debugging it looks like the input filters are empty.

**Comment by sanskar345** [comment]
In some instances, the Job is present on the BROKER_SYS_JOB group instead of ORDER_SYS_JOB which is why the job is not showing up.

**Comment by Dhiraj1405** [comment]
Since, we have different pages for fulfillment and brokering now. This issue is resolved
