### ISSUE TITLE
Login api should not be called on 'enter' if the username, oms or password field is empty

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/job-manager#557]
## Current behavior

When we have not entered all or any one of the fields from username, oms and password on the login page, then the user is not informed instantly, instead the login api is being called and a toast notification is being displayed.

## Expected behavior

When we have one or all the fields being empty, but if we click on the `Login` button, we get specific validation error and no api is being called. Same behavior is expected on `enter`.

## Steps to reproduce the issue

- Go to Login page
- Make any field empty
- Click on the `Login` button, verify a validation error being displayed
- Instead of clicking on button, use `enter` to submit the form, and verify a toast is being displayed and no validation error

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by sanskar345** [comment]
This issue is solved after Single Sign On implementation.
Note: This issue still reproduces where we have not implemented Single Sign On.
