### ISSUE TITLE
Allow users to pass their valid special parameters that are not available by default

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/job-manager#588]
## What is the motivation for adding/enhancing this feature?
Refer to this [Advanced-job-parameters PR FAQ](https://github.com/hotwax/press-release-faq/blob/main/job-manager/advanced-job-parameters.md)

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Key points: 

1. Advanced parameters are divided into two categories: Required and Optional. 
2. Required parameters can not be passed when empty, will always require data. 
3. Optional parameters can be empty.

**Comment by ymaheshwari1** [comment]
Closing as handled in https://github.com/hotwax/job-manager/pull/592
