### ISSUE TITLE
 Sort Completed Jobs from Latest to Oldest in the Completed Jobs Section

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/job-manager#594]
## Current behavior
Currently, the Completed Jobs section are sorted by their status which creates inconvenience for users in tracking and accessing the most recent completed jobs.

## Expected behavior
The Completed Jobs section should present completed jobs in descending order, with the latest completed job displayed first. Users should be able to easily find and review the most recently finished tasks at the top of the list.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
Closing as handled in #613
