### ISSUE TITLE
Resolve inconsistency in editing custom runtime after initial custom runtime configuration

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/job-manager#602]
## Current behavior
Users encounter varying behavior when attempting to change the custom runtime after the initial configuration. Sometimes, users can successfully change the custom runtime, while in other cases, they are unable to open the date time modal to change it. 

## Expected behavior
Users should be able to consistently change the custom runtime after it has been initially configured. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ymaheshwari1** [comment]
Might be fixed with https://github.com/hotwax/job-manager/pull/593
