### ISSUE TITLE
 Integrate DXP Component: App Version Info on the Settings Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/job-manager#618]
## What is the motivation for adding/enhancing this feature?
Integrate the DXP component "App Version Info" into the Settings page of the application. This addition will provide users with essential information about the version of the application they are currently using.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.23.2.
