### ISSUE TITLE
Brokering page flickering

### ISSUE THREAD

**Issue by dt2patel** [hotwax/job-manager#638]
## Current behavior

When opening a regular brokering job on the brokering page and then clicking on the rejected orders job, the page is flickering.

https://jam.dev/c/bdb6fdc3-8b2b-449e-941c-ec50704c59b1

**Comment by k2maan** [comment]
Unable to replicate.

**Comment by amansinghbais** [comment]
Unable to regenerate this issue, will reopen this if face this issue again.
