### ISSUE TITLE
Setting runtime for export threshold job to `now` with a zero threshold value results in a job failure

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/job-manager#642]
## Current behavior
When attempting to set the runtime for the export threshold job to "now" with a threshold value of zero, the job fails. It appears that there might be an issue with parsing zero values, possibly treating them as empty, leading to unexpected behavior.

## Expected behavior
The job should run successfully with a runtime set to "now" and a threshold value of zero.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by amansinghbais** [comment]
Job running properly without any failure for the specific case given in the issue.

**Comment by dt2patel** [comment]
Not using this job anymore
