### ISSUE TITLE
Set Master Shop as Default Shopify Shop for Users

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/job-manager#659]
## What is the motivation for adding/enhancing this feature?
Upon login or when accessing Shopify Shop, users should have their Master Shop automatically selected as the default shop. This eliminates the need for users to manually choose their shop each time and ensures a smoother workflow.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
@Dhiraj1405 
I think this ticket now can be discarded, as this should be covered in the following - 

https://github.com/hotwax/user-management/issues/112
https://github.com/hotwax/job-manager/issues/682

**Comment by dt2patel** [comment]
Linked ticket covers this by setting user preference
