### ISSUE TITLE
Dropdown Selection for 'Group By' Custom Parameter in Job Configuration

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/job-manager#681]
## Current behavior
When a 'group by' custom parameter is added to a job, there is no dropdown menu or selection interface provided for choosing values associated with this parameter.

## Expected behavior
The interface should present a dropdown menu or selection interface that allows users to choose values associated with the 'groupBy' parameter.

## Steps to reproduce the issue
Open the app and then navigate to the job configuration interface.
Add a 'group by' custom parameter to the job or open the job for which 'groupBy' custom parameter is already added.
Attempt to select values for the 'group by' parameter.
Observe that no dropdown menu or selection interface is available for choosing values.

## Environment details
- App version: 2.20.1
- Environment: UAT

## Additional information
https://jam.dev/c/b44317df-0d67-4417-8065-b380dc1591bf

**Comment by dt2patel** [comment]
We should remove this ticket since the data manager model is being refactored right now so we can't be sure what design we really want on the app side

**Comment by Adameddy26** [comment]
> We should remove this ticket since the data manager model is being refactored right now so we can't be sure what design we really want on the app side

Closing this ticket.
