### ISSUE TITLE
Enhance Job History Model to Include Currently Scheduled Jobs

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/job-manager#687]
## Description
Currently, users need to navigate to the pipeline to verify the status of currently scheduled and running jobs. This process can be cumbersome and inefficient, especially when users need quick access to this information. To improve user experience and streamline job management, we propose enhancing the Job History model to include details of currently scheduled and running jobs.

**Comment by Dhiraj1405** [comment]
Will recreate when raised by customer.
