### ISSUE TITLE
Need to remove BOPIS correction job from UI

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/job-manager#694]
## What is the motivation for adding/enhancing this feature?
The current UI includes a BOPIS Correction Job in inventory section that is no longer required. As a result, it needs to be removed from the UI to streamline the user experience and avoid confusion. This will require to remove the enumeration data from the backend.

**Comment by Adameddy26** [comment]
Enhancement verified and working fine in release v2.22.0. Hence, closing it.
https://jam.dev/c/262d3a7b-3a2c-4514-a4d0-8d5855e2e01b
