### ISSUE TITLE
Remove extra lines when displaying helper or error text for custom params and hide the copy option from custom params modal when no params are available

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/job-manager#698]
## Current behavior

- When displaying helperText or errorText for custom parameters, a separate line gets displayed for the helper/error text.
- If there are no custom params available then the copy button on the custom params modal should not be displayed as only an `{}` object is copied and there is no use case for having the button when there is no data inside the modal.

![image](https://github.com/hotwax/job-manager/assets/41404838/bec8a3bc-2e8b-40b0-aff6-16e57a1e1629)

## Expected behavior

- Only display a single line for custom params and remove the duplicate line
- Remove the copy icon from the modal when there is no data to copy inside the custom params modal

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

Check for the multiple lines case on all the places where we have used helper/error text.

**Comment by Adameddy26** [comment]
Issue verified in release v2.23.0 and found that issue is still there as no line is visible in between the optional custom parameters as seperator.
https://jam.dev/c/f962d025-73f8-4ea8-a4b5-610b86da47ab

**Comment by amansinghbais** [comment]
Fixed the above issue in following PR: https://github.com/hotwax/job-manager/pull/708

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.23.1. Hence, closing it.
