### ISSUE TITLE
Options to schedule Open BOPIS Order, Ready to pick BOPIS order and open shipping order notifications job from fulfillment/notifications section

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/job-manager#711]
## What is the motivation for adding/enhancing this feature?
Options to schedule Open BOPIS Order, Ready to pick BOPIS order and open shipping order notifications job from fulfillment/notifications section. This will help to control frequency of each type of notifications separately.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.23.2. Hence, closing it.
